src/components/SignUp/SignUp.js, src/components/SignUp/SignUp.module.css, src/components/SignUp/SignUpForm.js, src/components/SignUp/SignUpForm.module.css, src/pages/signup.js
=> [signup] 회원가입 페이지

src/components/Common/Header.js, src/components/Common/Header.module.sass, src/pages/index.js
=> Add(soonki/header): 스크롤 감지 헤더 생성, index.js에 헤더 적용

src/components/Notice/Notice.js, src/components/Notice/Notice.module.sass, src/components/Notice/NoticeSearch.module.sass
=> Add(junsang/notice): 공지게시판 검색창 글쓰기버튼 넣기

src/components/ClubHome/ClubNotice.js, src/components/ClubLists/ClubListContainer.js, src/components/ClubRegister/ClubRegisterForm.js, src/components/Notice/Notice.js, src/components/Notice/NoticeTable.js, src/components/SignUp/SignUpForm.js, src/components/SignUp/SignUpForm.module.css, src/components/Write/Write.js, src/components/login/Login.js, src/components/main/ClubBanner.js
=> Add(junsang/buttonLink): 페이지 버튼들 라우팅 링크 구현 #67

package.json, src/components/Common/Header.js, src/styles/Common/Header.module.scss
=> Modify(seohyun/Header): Header UI 1차 구현 #99

src/components/Promotion/PromotionContainer.js, src/components/Promotion/TypeSearch.js, src/components/Promotion/data.js, src/styles/Board/Promotion/PromotionContainer.module.scss, src/styles/Board/Promotion/typeSearch.module.scss
=> Modify(bumsoo/promotion): 홍보게시판 UI 개선

src/components/ClubHome/Activities/Activities.js, src/components/ClubHome/Activities/Modal.js, src/components/ClubHome/common/frame.js, src/styles/Club/Home/Activities/Act.module.scss, src/styles/Club/Home/Activities/Activities.module.scss, src/styles/Club/Home/Activities/Modal.module.scss, src/styles/Club/Home/Common/SideBar.module.scss, src/styles/Club/Home/Common/frame.module.scss, src/styles/Common/Header.module.scss
=> Add(soonki/activity): 1. modal 사진 전환 기능 추가 2. 활동내용 페이지 반응형 구현

src/components/SignUp/SignUpForm.js, src/components/login/Login.js, src/styles/User/Login/Login.module.scss, src/styles/User/SignUp/SignUp.module.scss, src/styles/User/SignUp/SignUpForm.module.scss
=> Modify(seohyun/login): 로그인 페이지 UI 개선

src/components/Find/FindID.js, src/components/Find/FindPW.js, src/components/login/Login.js, src/pages/findID.js, src/pages/findPW.js, src/styles/User/Find/FindID.module.scss, src/styles/User/Find/FindPW.module.scss
=> Add(seohyun/find): 아이디/비밀번호 찾기 페이지 생성 밎 ui 구현 후 라우팅

src/components/Promotion/Modal.js, src/components/Promotion/PromotionContainer.js, src/styles/Board/Promotion/Modal.module.scss, src/styles/Common/Header.module.scss
=> Add(bumsoo/promotion): 홍보게시글 Ui 추가

src/components/ClubHome/Activities/Activities.js, src/components/ClubHome/Activities/Modal.js, src/components/ClubHome/Activities/ModalFooter.js, src/components/ClubHome/Activities/ModalHeader.js, src/components/ClubHome/Activities/ModalImg.js, src/components/ClubHome/Apply/Apply.js, src/components/ClubHome/Apply/ApplyHeader.js, src/components/ClubHome/common/SideBar.js, src/components/ClubHome/common/frame.js, src/styles/Club/Home/Activities/Act.module.scss, src/styles/Club/Home/Activities/Activities.module.scss, src/styles/Club/Home/Activities/Modal.module.scss, src/styles/Club/Home/Apply/Apply.module.scss, src/styles/Club/Home/Common/SideBar.module.scss, src/styles/Club/Home/Common/frame.module.scss, src/styles/Club/Home/Review/ReviewMine.module.scss
1. 사이드바 580px 이하시 상단 가운데 정렬
2. 컴포넌트 전환 시 스크롤상단
3. 활동 내용 페이지 이미지 크기 조정
4. 활동 내용 modal svg 위치 조정
5. window is not defined 에러 해결
=> Modify(soonki/clubHome): 동아리 홈에서 5가지 수정

src/styles/Club/Home/Activities/Modal.module.scss, src/styles/global.scss
=> Refactor(soonki/font): global font 적용

src/components/ClubHome/Apply/Additional.js, src/components/ClubHome/Apply/Apply.js, src/components/ClubHome/Apply/ApplyHeader.js, src/components/ClubHome/Apply/ApplyQuestions.js, src/styles/Club/Home/Apply/Additional.module.scss, src/styles/Club/Home/Apply/Apply.module.scss, src/styles/Club/Home/Apply/ApplyHeader.module.scss, src/styles/Club/Home/Apply/ApplyQuestions.module.scss
=> Add(soonki/apply): 동아리 지원하기 페이지 생성 및 UI 구현

src/components/ClubHome/Manager/Approve.js, src/components/ClubHome/Manager/ApproveHeader.js, src/components/ClubHome/Manager/ApproveList.js, src/components/ClubHome/Manager/Manager.js, src/components/ClubHome/Manager/Members.js, src/components/ClubHome/Manager/MembersHeader.js, src/components/ClubHome/Manager/MembersMember.js, src/components/ClubHome/Manager/MembersPreface.js, src/styles/Club/Home/Manager/Approve.module.scss, src/styles/Club/Home/Manager/ApproveList.module.scss, src/styles/Club/Home/Manager/Manager.module.scss
=> Add(soonki/manager): 동아리 관리 페이지 가입 승인 대기 추가

src/components/Board/Board.js, src/components/Board/Pagination.js
=> Modify(junsang/board): 페이지네이션 url query로 동작 구현

src/components/ClubHome/Apply/ApplyQuestions.js, src/styles/Club/Home/Apply/Additional.module.scss, src/styles/Club/Home/Apply/Apply.module.scss, src/styles/Club/Home/Apply/ApplyHeader.module.scss, src/styles/Club/Home/Apply/ApplyQuestions.module.scss
=> Modify(soonki/apply): 동아리 지원하기 반응형 구현 #118

src/components/ClubHome/Review/Review.js, src/components/ClubHome/Review/ReviewFilter.js, src/components/ClubHome/Review/ReviewHeader.js, src/components/ClubHome/Review/ReviewList.js, src/components/ClubHome/Review/ReviewMine.js, src/components/ClubHome/Review/ReviewWrite.js, src/styles/Club/Home/Review/ReviewWrite.module.scss
=> Add(soonki/review): 동아리 후기 글 + 별점 추가 기능 구현

src/components/Common/Header.js, src/styles/Common/Header.module.scss
=> Modify(seohyun/Header): 헤더 반응형 및 UI 개선

src/components/ClubHome/Intro/ClubIntro.js, src/components/ClubHome/Intro/Desc.js, src/components/ClubHome/Review/Review.js, src/components/ClubHome/Review/ReviewMine.js, src/components/ClubHome/Review/ReviewWrite.js, src/styles/Club/Home/Intro/ClubIntro.module.scss, src/styles/Club/Home/Intro/Desc.module.scss
=> Add(soonki/intro): 동아리 소개 수정 api 적용

src/components/ClubHome/Review/Review.js, src/components/ClubHome/Review/ReviewWrite.js, src/styles/Club/Home/Activities/Activities.module.scss, src/styles/Club/Home/Common/SideBar.module.scss, src/styles/Club/Home/Intro/ClubInfo.module.scss, src/styles/Club/Home/Intro/ClubIntro.module.scss, src/styles/Club/Home/Intro/Desc.module.scss, src/styles/Club/Home/Notice/ClubNotice.module.scss, src/styles/Club/Home/Review/Review.module.scss, src/styles/Club/Home/Review/ReviewHeader.module.scss, src/styles/Club/Home/Review/ReviewList.module.scss, src/styles/Club/Home/Review/ReviewMine.module.scss, src/styles/Club/Home/Review/ReviewWrite.module.scss, src/styles/Common/Footer.module.scss
=> Fix(soonki/clubHome): 모바일 화면에서 사이드바가 깨지던 이슈 수정 #200

package-lock.json, package.json, src/components/Common/Header.js, src/components/login/Login.js, src/styles/Common/Header.module.scss
1. 로그인시 enter눌렀을때 submit 되도록 구현
2. 사이드바 ui  전면 수정
3. 영역 밖 클릭시 사이드바 close되도록 구현
4. 사이드바 클릭시 햄버거 아이콘 변형되도록 도입
=> Modify(seohyun/Header): 사이드바 UI 개선 및 기능 개선

src/components/Board/Board.js, src/components/ClubHome/Notice/ClubNotice.js, src/components/ClubHome/common/frame.js
컴포넌트 안에 함수를 만들고 그 안에서 컴포넌트를 생성한걸 반환하면
컴포넌트가 리렌더링될때 컴포넌트가 다시 생성되는 버그
usecallback을 사용해서 함수가 새로 생성되는 것을 방지
=> Fix(junsang/board): 동아리별 공지 게시판 페이지 변경시 리렌더링되는 버그 해결

src/components/Common/Comment/Comment.js, src/styles/Board/Board/Board.module.scss, src/styles/Board/Post/PostContent.module.scss, src/styles/Common/Comment/AddComment.module.scss, src/styles/Common/Comment/Comment.module.scss
게시판 제목 호버 색 변경 삭제
댓글작성 버튼, 답글 쓰기 커서 포인터
=> Modify(junsang/board): css 수정

src/apis/profile.js, src/components/Profile/Post.js, src/components/Profile/PostContainer.js, src/components/Profile/Profile.js
=> Fix(hyunwoo/profile): 마이페이지 스크랩글 삭제 오류 수정

src/components/Write/Write.js, src/styles/Board/Post/PostContent.module.scss, src/styles/Common/Comment/Comment.module.scss, src/styles/Common/Comment/ReplyContainer.module.scss
=> Modify(junsang/board): css 수정, 게시글 작성 최대 제목 제한

src/components/main/Intro.js
=> Modify(seohyun/main): 메인페이지 서비스 소개 이미지 변경

src/components/Common/Alarm/AlarmContainer.js, src/components/Common/Header/Header.js, src/styles/Common/Header/Header.module.scss
=> Add(soonki/alarm): 알람 갯수 표시

src/components/Board/Board.js, src/components/ClubHome/Activities/Act.js, src/components/Common/Comment/AddComment.js, src/components/Common/Comment/Comment.js, src/components/Common/Comment/ReplyContainer.js, src/components/Post/Post.js, src/components/Write/WriteContent.js, src/styles/Board/Post/PostContent.module.scss, src/styles/Board/Write/Container.module.scss, src/styles/Board/Write/WriteContent.module.scss, src/styles/Club/Home/Activities/Act.module.scss, src/styles/Club/Home/Activities/Activities.module.scss, src/styles/Common/Comment/AddComment.module.scss, src/styles/Common/Comment/ReplyContainer.module.scss
게시글
- 전체공지 관리자만 작성
- 페이지 검색 버그 수정
- 제목 255자 제한
- 게시글 본문 폰트 사이즈 수정
- 답글 화살표 위치 수정
- 댓글란 등록란 마진 추가
글작성 
- 본문 min-height 추가
- 푸터 마진 추가
- 글작성 폰트 변경
- 테이프 삭제
- 글 삭제 물어보기 추가
- 글작성 툴바 보더 추가
활동내역 
- 활동내역 max-height 추가
- 제목 눌러도 글 볼수있는 기능 추가
- 모바일에서 한줄에 2개씩 보여지게 수정
=> Modify(junsang/board): 수정내용 수정

src/apis/image.js, src/components/Common/Alarm/AlarmBody.js, src/components/Common/Alarm/AlarmContainer.js, src/components/Common/Alarm/AlarmList.js, src/components/Common/Header/Header.js, src/styles/Common/Alarm/AlarmContainer.module.scss, src/styles/Common/Header/Header.module.scss
1. 알림 삭제 누르고 나서 ⇒ 지워졌다는 메세지(?) 보였으면 좋겠음~~ 
2. 알림 누르면 해당하는 곳으로 이동하는 것
3. ~~학번 ⇒ 이름으로 수정~~
4. 종 모양 옆의 숫자가 움직임
=> Modify(soonki/alarm): 알람 수정사항 적용

src/components/ClubHome/Daily/Calendar.js, src/components/ClubHome/Daily/Control.js, src/components/ClubHome/Daily/DailyModal.js, src/components/ClubHome/Daily/MonthDays.js, src/components/ClubHome/Daily/OtherDays.js, src/components/ClubHome/Daily/ScheduleModify.js, src/components/ClubHome/Daily/TodayTd.js, src/styles/Club/Home/Schedule/Schedule.module.scss, src/styles/Club/Home/Schedule/Table.module.scss
=> Fix(hyunwoo/calendar): 수정사항 반영

src/components/ClubHome/Apply/Apply.js, src/components/ClubHome/Apply/ApplyQuestions.js, src/styles/Club/Home/Apply/Apply.module.scss
1. ~~핸드폰 번호 형식 검증해주기 (프론트, 백)~~
2. ~~셀렉트 박스의 크기가 너무 작다.~~
3. ~~멤버 추방 후 가입 신청 안됨~~
4. ~~학년 성별 휴대전화 기입 안되도 신청 가능한 거 처리해주기(프론트, 백)~~
=> Modify(soonki/apply): 동아리 지원하기 페이지 수정사항 적용

src/components/main/ClubPromotion.js, src/styles/Main/ClubPromotion.module.scss, src/styles/Main/Intro.module.scss
1. 이런 서비스를 제공해요 안쪽으로 넣음
2. 다크모드시 섹션 분리 안되도록 수정
=> Modify(seohyun/main): 메인 피드백 반영

src/styles/Board/Promotion/PromotionContainer.module.scss, src/styles/Board/Promotion/typeSearch.module.scss
=> Fix(bumsoo/promotion): 화면 커질 때 깨지는 오류 수정

package-lock.json, package.json, src/components/Common/Footer.js, src/styles/Common/Footer.module.scss, src/styles/Main/ClubPromotion.module.scss, src/styles/Main/Intro.module.scss, src/styles/Main/OurIntro.module.scss, src/styles/User/ChangePassword/ChangePassword.module.scss, src/styles/User/Find/FindID.module.scss, src/styles/User/Find/FindPW.module.scss, src/styles/User/Find/ResetPW.module.scss, src/styles/User/Login/Login.module.scss, src/styles/User/SignUp/SignUpForm.module.scss
=> Modify(seohyun/style): 전체적인 css 보완 및 footer ui 변경

src/components/ClubHome/Activities/Activities.js, src/components/ClubHome/Intro/ClubIntro.js, src/components/ClubHome/Review/ReviewHeader.js
1. 동아리 활동내용 동아리 이름 동적 적용
2. 리뷰 없을 시 NaN x
3. 이미지 리사이징 문제 해결
=> Fix(soonki/issue): 각종 이슈 해결

src/components/Common/Header/Header.js, src/styles/Common/Header/Header.module.scss
=> Modify(seohyun/header): 헤더 사용자 프로필 사진 썸네일 추가

src/apis/promotion.js, src/components/Promotion/Comment/AddComment.js, src/components/Promotion/Comment/Comment.js, src/components/Promotion/Comment/PromotionCommentContainer.js, src/styles/Board/Promotion/Post.module.scss
=> Fix(bumsoo/promotion): 대댓글 오류 및  게시글 사진 사이즈 조절 

src/components/Profile/ModifyInfo/ModifyInfo.js
동아리 탈퇴부분은 에러뜨면 함수 실행 안돼서 수정 필요없음
=> Fix(hyunwoo/profile): 프로필 수정시 jwt 토큰 오류 수정

src/components/Common/Alarm/AlarmBody.js, src/components/Common/Alarm/AlarmContainer.js, src/components/Common/Alarm/AlarmList.js, src/components/Common/Header/Header.js
1. 알람 없을 시 메시지 추가
2. 알람 클릭을 통해서 페이지 이동 시 알람 삭제
3. get요청 오류 발생 alert 제거
=> Modify(soonki/alarm): 알람 기능 수정

src/components/ClubHome/Intro/ClubIntro.js, src/components/ClubHome/common/frame.js
=> Fix(soonki/clubhome): 동아리 홈에서 알람 라우팅 시 동아리 명이 다르게 나오던 오류 수정

src/components/Common/Comment/Comment.js, src/styles/Board/Board/Board.module.scss
=> Modify(junsang/board): 게시판 footer 맨밑으로 수정

src/styles/Board/Write/WriteContent.module.scss
=> Add(junsang/board): 에디터 툴바 고정 sticky 수정

src/components/Board/Table.js, src/components/Common/Comment/Comment.js, src/components/Post/Post.js, src/styles/Board/Post/PostContent.module.scss, src/styles/Common/Comment/Comment.module.scss
=> Add(junsang/board): 좋아요 버튼 추가

src/components/Profile/MyItems.js, src/components/Profile/MyPost.js, src/styles/Profile/MyPost.module.scss, src/styles/Profile/Profile.module.scss
=> Fix(hyunwoo/profile): map 함수 반환하는 태그에 key 값 부여

src/components/Board/Table.js, src/styles/Board/Board/Table.module.scss
=> Modify(junsang/board): 게시판 댓글, 좋아요 수정

src/styles/Common/Header/Header.module.scss
=> Modify(seohyun/header): 헤더 기존 프로필 사이즈 조절

src/components/Message/DetailMessageList.js, src/components/Message/DetailMessageListContainer.js, src/components/Message/EntireMessageList.js, src/components/Message/MessagePreview.js, src/styles/Message/DetailMessageList.module.scss, src/styles/Message/MessageList.module.scss, src/styles/Message/MessagePreview.module.scss
*** 범수오빠 해야할 것 ***
1. 쪽지 보낸/받은 메세지함 스크롤 됐을 때 height 맞춰주기
2. 반응형 했을 때 문제없는지 확인하기 (있다면 기존 베이스에 맞춰 수정)
3. 쪽지가 아예 없을때 '아직 쪽지가 없습니다'와 같은 멘트 body에 넣어주기
4. 양 옆 container body스크롤 됐을때 문제 없는지 확인 (반응형도 마찬가지)
=> Modify(seohyun/message): 쪽지함 ui 수정

src/apis/promotion.js, src/components/Common/Alarm/index.js, src/components/Common/letter/index.js, src/components/Message/SendMessage.js, src/components/Promotion/Comment/AddComment.js, src/components/Promotion/Modal.js, src/components/Promotion/Promotion.js, src/components/Promotion/PromotionContainer.js, src/styles/Board/Promotion/Promotion.module.scss, src/styles/Board/Promotion/PromotionContainer.module.scss, src/styles/Club/Lists/ClubLists.module.scss
=> Modify(bumsoo/promotion): 홍보게시판 레이아웃 변경 

src/styles/Common/Badge.module.scss
=> Modify(soonki/badge): 뱃지 넓이 변경

src/components/ClubHome/Activities/Act.js, src/components/ClubHome/Activities/Activities.js, src/styles/Club/Home/Activities/Act.module.scss
=> Modify(seohyun/activity): 활동내용 이미지 없는 썸네일 변경

src/components/Club/Home/Manager/index.js
#747 
https://github.com/wooahan-agile/dongurami-server/issues/66
=> Delete(soonki/manager): 가입 승인 거절 body에서 필요없는 내용 제거 #747

src/apis/alarm.js, src/components/Club/Home/Manager/index.js
=> Add(soonki/manager): 가입 승인 거절 알람 API 추가 #747

src/apis/post.js, src/components/Common/Comment/AddComment.js, src/components/Post/Post.js, src/redux/slices/board.js
Fix(hyunwoo/board): api 수정사항 반영
=> Fix(hyunwoo/board): api 수정사항 반영

src/components/User/Profile/MyPost/MyPost.js, src/components/User/Profile/Scraps/ScrapItems.js, src/components/User/Profile/Scraps/Scraps.js, src/components/User/Profile/Scraps/WriteScraps/Edit.js, src/components/User/Profile/Scraps/WriteScraps/PostContainer.js, src/components/User/Profile/Scraps/WriteScraps/WriteScraps.js, src/components/User/Profile/index.js
=> Fix(hyunwoo/profile): 스크랩페이지 api 응답데이터 키값 수정
